### ISSUE TITLE
Internal constructor causes vague exception message

### ISSUE THREAD

**Issue by ryan-codingintrigue** [aspnet/DependencyInjection#182]
I've just spent a decent amount of time trying to debug the following exception:

> System.ArgumentNullException
> Object cannot be null.
> Parameter name: source
> 
> at
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(Exception
> source)  at
> Microsoft.Framework.DependencyInjection.ServiceLookup.Service.CreateInstanceCallSite.Invoke(ServiceProvider
> provider)  at
> Microsoft.Framework.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider
> provider)  at
> Microsoft.Framework.DependencyInjection.ServiceLookup.Service.ConstructorCallSite.Invoke(ServiceProvider
> provider)  at
> Microsoft.Framework.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider
> provider)  at
> Microsoft.Framework.DependencyInjection.ServiceProvider.<>c__DisplayClass8_0.<RealizeService>b__0(ServiceProvider
> provider)  at
> Microsoft.Framework.DependencyInjection.ServiceProvider.GetService(Type
> serviceType)  at
> Microsoft.Framework.DependencyInjection.TypeActivator.ConstructorMatcher.CreateInstance(IServiceProvider
> _services)  at Microsoft.Framework.DependencyInjection.TypeActivator.CreateInstance(IServiceProvider
> services, Type instanceType, Object[] parameters)  at
> Microsoft.AspNet.Mvc.DefaultControllerFactory.CreateController(ActionContext
> actionContext)

Turns out all that was wrong was the constructor for my concrete implementation was marked as `internal`. Changing it to `public` works fine. I understand why, but the exception message was not helpful in trying to diagnose the issue.

**Comment by davidfowl** [comment]
Do you want to send a PR for this?

**Comment by ryan-codingintrigue** [comment]
I can certainly give it a go

**Comment by mdekrey** [comment]
This exception also crops up when there's multiple public constructors on the class being instantiated. 

I believe this is fixed with [this commit by @davidfowl][0] - adding the conditional `when (ex.InnerException != null)` should do it. Unfortunately, I'm not running against the daily builds so I can't confirm.

[0]: https://github.com/aspnet/DependencyInjection/blob/7326ec5166695adeb9718175b546e71077b8c448/src/Microsoft.Framework.DependencyInjection/ServiceLookup/Service.cs
