### ISSUE TITLE
Add profile 259 support

### ISSUE THREAD

**Issue by sblackler** [aspnet/DependencyInjection#233]
Currently the framework only supports Profile7. I would like to see expanded support for Profile259 so that we can use the abstractions here in more scenarios as we build our class libraries.

**Comment by Eilon** [comment]
Can you verify if the new `dotnet` target that this package has already supports this?

**Comment by pranavkm** [comment]
The `dotnet` profile isn't compatible with any PCL frameworks. There's a feature in NuGet v3 (https://github.com/NuGet/Home/issues/922) that allows working around this, but it only works 
* project.json based projects
* applications consuming packages and not package authors (since `allowAlso` does not appear in the nuspec).

My guess is we'll see more libraries switch to targeting `dotnet` so perhaps we can leave this as is? cc @davidfowl, thoughts?

**Comment by Eilon** [comment]
It is certainly the case that we want package authors to use `dotnet` whenever possible.

**Comment by Eilon** [comment]
Putting in RC so that once generations is online we can verify the behavior in those circumstances.

**Comment by pranavkm** [comment]
@davidfowl this probably shouldn't be an issue now with `imports` + cli. Does that sound right?

**Comment by pranavkm** [comment]
This should be achievable via `imports` section supported by dotnet-cli. The import section would probably look like; `imports": "portable-net45+win8+wp8". See https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/project.json#L43 for an example.
