### ISSUE TITLE
User information injection

### ISSUE THREAD

**Issue by IonRobu** [aspnet/DependencyInjection#290]
Hello,

I have an object containing informations about current user. I want to inject the object as transient (per request) in a layer where user info is not available (no reference to Web dependencies). Is there a way to init this object on every request (as old Begin_Request handler) with current user info (such username etc)?

Thanks,
Ion

**Comment by rynowak** [comment]
Disclaimer - I'd suggest being really careful with this pattern. Using DI in this way makes you really sensitive to *when* you are getting things from DI and what their lifetime is. If you do this wrong and have a bug, the result will be crosstalk between users - one user's request executing with another user's credentials.

You can do something like the following:

- register a **scoped** service `IUserAccessor` like this:
```
public interface IUserAccessor
{
    public User CurrentUser { get; set; }
}
```
- register `User` as a transient using a factory like this:
```
services.AddTransient<User>((services) => services.GetRequiredService<IUserAccessor>().CurrentUser);
```

- Lastly, add some kind of middleware that DIs `IUserAccessor` and sets `CurrentUser` early in the pipeline. Because `IUserAccessor` is scoped, it will be durable for the rest of the request.
