### ISSUE TITLE
Open generic service type x requires registering an open generic implementation type

### ISSUE THREAD

**Issue by SYoungPB** [aspnet/DependencyInjection#311]
I have a service with a constructor parameter expecting `IDependency<T>`. I have registered a dependency `IDependency<T>` -> `MyDependency` where `MyDependency : IDependency<MyClass>` but this throws the above `System.ArgumentException`.

Is there a reason why this is not valid?

**Comment by Eilon** [comment]
I think the error is correct. How would the system know that any type depending on any variation of `IDependency<T>` should always get `MyDependency` as the implementation? And what if they're incompatible?

For example, what if a type depended on `IDependency<Banana>`? If the DI system tried to give it an instance of `MyDependency` then it would fail because `MyDependency` doesn't implement `IDependency<Banana>`.
