### ISSUE TITLE
[Discussion]: AddInstance was renamed to AddSingleton

### ISSUE THREAD

**Issue by pranavkm** [aspnet/DependencyInjection#332]
Discussion PR for #319

The rename makes the 3 APIs line up 

``` C#
AddSingleton<IService, MyService>();

AddSingleton<IService>(serviceProvider => new MyService(serviceProvider));

AddSingleton<IService>(new MyService());
```

**Comment by NeelBhatt** [comment]
:+1:

**Comment by pebezo** [comment]
https://docs.asp.net/en/latest/fundamentals/dependency-injection.html

> One key difference between Instance services and Singleton services is that the Instance service is created in ConfigureServices, while the Singleton service is lazy-loaded the first time it is requested.

So if you "merge" or rename, how would the new functionality fit? How would I know where the instance is created?

**Comment by pranavkm** [comment]
That doesn't change. You're still passing in an instance so it's instantiated wherever you're create it.

**Comment by pebezo** [comment]
Duh, good point :smile:

**Comment by matlus** [comment]
Should probably call is AddSingleInstance() instead?

**Comment by pranavkm** [comment]
@matlus, we don't differentiate between the factory method and the type overload (i.e. we don't have a `AddSingletonFactory`) and we haven't had any issues with that as yet. I'm not sure why the instance overload would warrant a different method name.

**Comment by matlus** [comment]
@pranavkm I don't see a Singleton needs a Factory (since there is only one).

AddInstance is clearer (to me) than AddSingleton in my honest opinion.

I guess the confusion is that "Singleton" is an overloaded term here. I assumed (initially) my class needed to be designed as a Singleton, but we're say "give me an instance and I'll just reuse that instance each time". so it's effectively a singleton but it is not designed to be.

Thinking back on it, I'd stick to AddInstance() :). code documentation in these methods will make the intent/operation clearer.

**Comment by Eilon** [comment]
A singleton could need a factory if it is expensive or complex to construct, yet might not be needed.

**Comment by pranavkm** [comment]
The factory lets you get at other services via the service container that is passed to it. We use this in a couple of places as a substitute for creating instance factories.

**Comment by matlus** [comment]
>The factory lets you get at other services via the service container that is passed to it. We use this in a couple of places as a substitute for creating instance factories.

Right, that's exactly what I use the AddInstance() for now. But I create the instance and hand it off (obviously). So you're saying the overload that takes a Factory method, will use the Factory method just once? Or do I have to pass you a method that creates an instance where the class is designed to be a singleton?

Ok, looking at Eilon's answer makes sense from a lazy loading need point of view. I see the use for this functionality (obviously - since I'm using it :smiley:). I do still have a confusion with the name.

**Comment by davidfowl** [comment]
> So you're saying the overload that takes a Factory method, will use the Factory method just once?

Yes it will be called just once, since it's a singleton.

> Or do I have to pass you a method that creates an instance where the class is designed to be a singleton?

Yes, if you add a singleton the class should be designed to be a singleton.

> Ok, looking at Eilon's answer makes sense from a lazy loading need point of view. I see the use for this functionality (obviously - since I'm using it :smiley:). I do still have a confusion with the name.

The delegate is not just for lazy loading, it's for getting at other registered services at time of construction:

```C#
services.AddSingleton<IFoo>(sp => new Foo(sp.GetRequiredService<IBar>());
```

At the time you call `AddSingleton(instance)` you may not have access to everything required to construct the instance.

**Comment by matlus** [comment]
I get the need/purpose of this method and its overloads. By the way does the DI container call Dispose for any instances it is managing and the type implements IDisposable?

**Comment by Eilon** [comment]
@matlus only one instance will be created. The class must be thread-safe or otherwise provide some sort of thread safety guarantee (e.g. a very poor solution would be some kind of external synchronization, but that's an extreme anti-pattern).

The class does not need to *require* allowing only one instance. In fact, that is also an anti-pattern. E.g. in a unit test you might want to instantiate many instance of the class to test.

**Comment by sebastienros** [comment]
I see that the overload `AddInstance(Type type, object instance)` has been removed, not just renamed as expected. I am opening an issue as this is blocking me right now.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
