### ISSUE TITLE
Multiple Service registration, IEnumerable and Unity

### ISSUE THREAD

**Issue by slaneyrw** [aspnet/DependencyInjection#432]
I have a question regarding the registration of services, specifically in regards to behaviour of `GetService<T>` and GetService`<IEnumerable<T>>`

My understanding is the ServiceCollection / ServiceProvider basically work on the principle of a linked list.

When using `GetService<T>`, the service provider finds the first registration of T, then walks the list of all other registrations of T until the last one is returned.

When using `GetService<IEnumerable<T>>`, the service provider files the first registration of T, adds it to the resolved list, finds the next, adds it the list, and so on until all registrations of T as resolved.

Unity makes a clear distinction between services that are single use and services that are expected to be resolved as a collection, but I cannot see that distinction in the ServiceCollection implementation or the ServiceDescriptor.  This is causing a problem for an Unity Container based IServiceProvider implementation.

I started a brand new AspNetCore MVC project and checked out the state of the service collection at the end of the ConfigureServices function in startup.  There were 188 registrations in the ServiceCollection.

There are 9 registrations for Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer.

If I call `GetService<Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer>()` I get the last registered - Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebUserTelemetryInitializer

If I call `GetService<IEnumerable<Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer>>` I get all 9.

In this case I think I can assume that ITelemetryInitializer is expected to be resolved as an IEnumerable but there is nothing in the ServiceDescriptor or service collection/provider that enforces this.

Therefore any type can be resolved either as 1 or Many.  For example, the type Microsoft.AspNetCore.Hosting.IHostingEnvironment does not make sense to be resolved as a collection of.

Nor can I make any assumptions that if there are multiple registrations then it should be resolved as `IEnumerable<>`.  For example there are two Descriptors for Microsoft.AspNetCore.DataProtection.Internal.IActivator, both point to Microsoft.AspNetCore.DataProtection.RC1ForwardingActivator with a singleton lifetime - this appears to be a duplicate registration

Your thoughts ?

**Comment by herecydev** [comment]
If there's not supposed to be multiple registrations, you can use the [TryAdd extensions](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/Extensions/ServiceCollectionDescriptorExtensions.cs), this preserves the original `ServiceDescription`. Alternatively, you can use the [GetServices extension](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceProviderServiceExtensions.cs#L88) and call `.Single()` or `.First()` on that if you don't have control of all the services being added. Finally, moving the ordering that the `ServiceCollection` is modified in will affect the outcome of `GetService()`. 

I think there's plenty of options to control the outcome.

> Therefore any type can be resolved either as 1 or Many. For example, the type Microsoft.AspNetCore.Hosting.IHostingEnvironment does not make sense to be resolved as a collection of.

 I don't think you can apply restrictions on what is or isn't applied when you don't control all the registrations. Do you expect an exception to occur if a duplicate has been registered? What happens if this isn't your code, how do you fix this?

**Comment by davidfowl** [comment]
We're looking at making this a little more clear by relaxing some of the requirements. You can follow the progress on this PR https://github.com/aspnet/DependencyInjection/pull/416#issuecomment-233188019

**Comment by slaneyrw** [comment]
Making sure dev's use `TryAdd` instread of `Add` to enforce cardinality leaves far too many holes.  There are many circumstances where a framework will want to override an implementation.  `TryAdd` will not allow that behaviour.

Been reading over PR 416 with interest... looks like a lot of the existing containers are having problems with cardinality.

**Comment by herecydev** [comment]
> There are many circumstances where a framework will want to override an implementation

Isn't that what `Add` is effectively doing when combined with `GetService()` or `GetRequiredService()`. You're not truly replacing it, but the effect is the same.

**Comment by slaneyrw** [comment]
But the intent is different, as well the results of `GetServices()` - note the plurality

**Comment by Eilon** [comment]
Closing because there are no plans to change this behavior.
