### ISSUE TITLE
Get all registered generic classes

### ISSUE THREAD

**Issue by ChrisProlls** [aspnet/DependencyInjection#444]
In our ASP.NET Core project, we registered generic classes in DI for cache management. In that way, we can partition the cache in logical part following the generic parameter that we inject.
`services.AddSingleton(typeof(IMemoryCacheManager<>), typeof(MemoryCacheManager<>));`

And we inject it like this :
```
IMemoryCacheManager<Class1> cache
IMemoryCacheManager<Class2> cache
```

But sometimes I need to get all instances of IMemoryCacheManager in one time, to clear the cache (for exemple). Can I achieve this with DI ?

This code compile :
```
var services =_serviceProvider.GetServices(typeof(IMemoryCacheManager<>));

foreach (ICacheManager item in services)
    item.Clear();
```

But I have this exception : The number of generic arguments Provided is not equal to the arity of the generic definition types

**Comment by khellang** [comment]
> But I have this exception : The number of generic arguments Provided is not equal to the arity of the generic definition types

This is because, if you look at [the source](https://github.com/aspnet/DependencyInjection/blob/60ca512beec3fefb4cd377ede009ff96b4848456/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceProviderServiceExtensions.cs#L116), that method simply wraps the type you give it in an `IEnumerable<T>`, so you're trying to resolve `IEnumerable<IMemoryCacheManager<>>`, which doesn't work.

I don't think this is possible... Think about it; how would you know which concrete services to resolve? There's basically a very important piece of information missing.

What you need to do, is introduce a `IMemoryCacheManagerManager` that keeps track of what managers you've already resolved so you can get a reference to and clear them :stuck_out_tongue_closed_eyes:

**Comment by ChrisProlls** [comment]
Ok, I see ;)
Too bad the code looks pretty nice.
