### ISSUE TITLE
Return whether TryAdd succeeded or not

### ISSUE THREAD

**Issue by sebastienros** [aspnet/DependencyInjection#447]
I need to register a service if it's not already defined, hence I use `TryAdd`. However I need to register another one with this, which I could do if `TryAdd` was returning whether or not it succeeded.

**Comment by josephgardner** [comment]
This change was previously attempted with #353.

@Eilon didn't see the value:
> honestly I can't see the use for it - it just hasn't come up in years. But I'd like to know more about what I'm missing here.

Just to add my own scenario; the host environment can optionally supply an implementation for some service to my middleware. If no service is provided, I want to register a default implementation. I can use `TryAdd` to accomplish this, however **I want to log** that the default service was used as a warning to the user since it should not be used in production.

Since this extension does not let me know success/fail, I am forced to write my own which returns a bool.

**Comment by khellang** [comment]
I'll just quote myself from https://github.com/aspnet/DependencyInjection/pull/353#issuecomment-178206877:

> Trust me - this'll come up time and time again :wink:

**Comment by Eilon** [comment]
Closing because this would be a fairly large breaking change with fairly low value.

**Comment by sebastienros** [comment]
Did you invert the words `large` and `low` on purpose ;)

**Comment by Eilon** [comment]
I'll leave that as an exercise to the reader 😄
