### ISSUE TITLE
New feature requirement – named service DI

### ISSUE THREAD

**Issue by smartmaster** [aspnet/DependencyInjection#473]
**_New feature requirement – named service DI_**

**Use case:**
Want to use different instances of same type of services.

**Preferred code:**
```
services.AddSingleton<IQueue>("Idle", …);
services.AddSingleton<IQueue>("Normal" , …);
services.AddSingleton<IQueue>("Realtime" , …);
```

**Do not like:**
```
class Queue : IQueue
{
    //methods
}

class IdleQueue : Queue
{
    //nothing here
}

class NormalQueue : Queue
{
    //nothing here
}

class RealtimeQueue : Queue
{
    //nothing here
}

services.AddSingleton<IdleQueue>(…);
services.AddSingleton<NormalQueue>(…);
services.AddSingleton<RealtimeQueue>(…);

```

**Comment by smartmaster** [comment]
@herecydev, thanks for your inputs. 

here are more clarifications and a concrete example.
Where the name is just name whatever can be specified, it is not related to types.
suppose i want to use 2 queues of type IList<string>, one for low priority and another for high priority.

1. add named services
```
services.AddSingleton<IList<string>>("low" , sp => new List<string>()); //expected in future
services.AddSingleton<IList<string>>("high" , sp => new  List<string>());
```

2. constructor DI for example
```
 public class MyController
    {
        public MyController(
            [FromServices("low")]     IList<string> lo, //expected in future
            [FromServices("high")]    IList<string> hi)
        {
            //....
        }
    }
```


it does not lose any type safety. DI should lookup servicess by both given name and type instead of only type. without the given names, there are workaround and  the workaround would be tricky.

**Comment by herecydev** [comment]
I see. It does look like some other frameworks have this functionality. I don't really like it though, surely asking for a specific implementation of a service breaks IoC? Ninject has this: `Bind<IWarrior>().To<Samurai>().WhenInjectedInto(typeof(OnLandAttack));` which I feel is better. But the general philosophy is that the majority, if not all, IoC containers should have this functionality for the `Microsoft.Extensions.DependencyInjection` to include it.

What reasons are there, in your example, for asking for specific implementations?

**Comment by brockallen** [comment]
I have used named registrations in DI to achieve decorator patterns. It's very useful.

**Comment by davidfowl** [comment]
Sadly I don't think we'd add this simply because not enough of the other DI framework adapters don't support it.

**Comment by Eilon** [comment]
For the reasons @davidfowl mentions, we are not planning to implement this.

**Comment by axelbodo** [comment]
I don't agree with herecydev, Spring, maven and unity does it, and we ask not for specifiy implementation, but for specific qualifier in a specific context.
I gladly welcome if aspnet dependency would go closer a springboot like vision, because some design pattern cannot be solved with the current service provider implementation, for example AContent class needs an ITemplate, and BContent class do so, I'd imagein something like this (@davidfowl it is common most of the DI frameworks I know):

`class AContent {
  public AContent([Qualifier("ATemplate"] ITemplate template)...
}

class BContent {
  public AContent([Qualifier("BTemplate"] ITemplate template)...
}`

This definitely typesafe would add value, and would bring aspnet core DI closer and autowiring paradigm.
