### ISSUE TITLE
Add an IServiceCollection.AddAssembly extensions method

### ISSUE THREAD

**Issue by lodejard** [aspnet/DependencyInjection#76]
to assist in clean startup, usage optional by application of course

AddAssembly(assembly) extension method scans for public types 

If the public type is creatable (class, non abstract) and a [ServiceDescriptorAttribute], add it to collection

ServiceDescriptorAttribute has a Lifecycle property, default is transient

ServiceDescriptorAttribute has a ServiceType property, default is null, null means add each interfaces.

**Comment by Antaris** [comment]
I took a different approach to this. As detailed in herehttp://stackoverflow.com/questions/31119284/getting-interface-implementations-in-referenced-assemblies-with-roslyn.

I wanted to avoid assembly scanning and reflection so I used a compile module to search simply for an instance of an module interface and then generated a type implementation at compile time with references to those modules. Each module returns service descriptors so they own their own service registrations. An arbitrary order can be applied as part of the interface contract.

It can pick up modules defined in compilations and references and the only requirement is to drop on a compile module into the host project.

Let me know your thoughts I can push a more concrete example to Github if need be

**Comment by taspeotis** [comment]
I'd like this too, please. MEF does this well with `new DirectoryCatalog("MyProject.*.dll")` which then looks for MEF attributes. I know DNX/CoreCLR has stripped down reflection capabilities (e.g. restrictions on assembly loading ... no `Assembly.GetReferencedAssemblies`) so I have rolled-my-own in a slightly different way.

(I prefer some sort of control over what is added to the container. If you scan for every type that's trivially constructible through a parameter-less constructor then I think you will pollute the container with a whole bunch of `MyProject.Entities.A ... B ... C` because entities are frequently POCOs.) 

There is one interface and three attributes

* `IAddServiceAttribute` (I believe this is "best practice" to avoid a base `AddServiceAttribute` class because attributes are meant to be `sealed`) - has `Type Interface { get; }` and `Type Implementation { get; }`
* `AddScopedAttribute`
* `AddSingletonAttribute`
* `AddTransientAttribute`

Usage is thus:

```csharp
using System;
using ...;

[assembly: AddScoped(typeof(IFooService), typeof(FooService)]

namespace MyProject {
  internal sealed class FooService : IFooService {
    ...
  }
}
```

And in `Startup.cs`

```csharp
// FromAssembly<TType> resolves the assembly of TType and then calls GetCustomAttributes x 3
// AddMyProject takes care of calling options.FromAssembly with its own type
services.AddMyProject(options => options.FromAssembly<Startup>());
```

(Whether `Assembly.GetCustomAttributes` is faster than `Assembly.GetTypes().Where(...)` is an open question but it feels more direct.)

Note open generics are permitted via `[AddWhatever(typeof(IRepo<>), typeof(Repo<>))]`.

I understand that ASP.NET DI is trying not to be opinionated and compatible with bring-your-own-container but some sort of auto-discovery with built-in `ConventionBasedDiscovery` (given all or a list of assemblies, add constructible types) and/or `AttributeBasedDiscovery` (give all or a list of assemblies, reads custom attributes).

I will state again I'm not in favour of blindly scanning all assemblies and types and adding them but it has its place.

**Comment by khellang** [comment]
I thought I already left this here, but apparently not, so here it goes... My approach; https://github.com/khellang/Scrutor

**Comment by khellang** [comment]
It doesn't look good for a built-in feature, though:

From https://github.com/aspnet/DependencyInjection/issues/322#issuecomment-157114371:

> We don't have any plans to include this functionality in the default container. The default container is deliberately minimalistic. For a full featured container you can use any of the various existing containers.

**Comment by davidfowl** [comment]
Definitely have a look at https://github.com/khellang/Scrutor for features like this.
